// Generated by delombok at Sat Oct 12 00:30:19 BRT 2024
package com.tiduswr.view;

import com.tiduswr.model.PlayerCardData;

/**
 * Classe que representa um evento de adição de uma carta no tabuleiro.
 * Contém informações sobre a carta adicionada e suas cartas adjacentes.
 */
public class CardAddedEvent {
    /**
     * A carta que foi adicionada
     */
    private PlayerCardData card;
    /**
     * A carta acima da carta adicionada
     */
    private PlayerCardData top;
    /**
     * A carta abaixo da carta adicionada
     */
    private PlayerCardData bottom;
    /**
     * A carta à esquerda da carta adicionada
     */
    private PlayerCardData left;
    /**
     * A carta à direita da carta adicionada
     */
    private PlayerCardData right;

    /**
     * A carta que foi adicionada
     */
    public PlayerCardData getCard() {
        return this.card;
    }

    /**
     * A carta acima da carta adicionada
     */
    public PlayerCardData getTop() {
        return this.top;
    }

    /**
     * A carta abaixo da carta adicionada
     */
    public PlayerCardData getBottom() {
        return this.bottom;
    }

    /**
     * A carta à esquerda da carta adicionada
     */
    public PlayerCardData getLeft() {
        return this.left;
    }

    /**
     * A carta à direita da carta adicionada
     */
    public PlayerCardData getRight() {
        return this.right;
    }

    /**
     * A carta que foi adicionada
     */
    public void setCard(final PlayerCardData card) {
        this.card = card;
    }

    /**
     * A carta acima da carta adicionada
     */
    public void setTop(final PlayerCardData top) {
        this.top = top;
    }

    /**
     * A carta abaixo da carta adicionada
     */
    public void setBottom(final PlayerCardData bottom) {
        this.bottom = bottom;
    }

    /**
     * A carta à esquerda da carta adicionada
     */
    public void setLeft(final PlayerCardData left) {
        this.left = left;
    }

    /**
     * A carta à direita da carta adicionada
     */
    public void setRight(final PlayerCardData right) {
        this.right = right;
    }

    @java.lang.SuppressWarnings("all")
    public CardAddedEvent(final PlayerCardData card, final PlayerCardData top, final PlayerCardData bottom, final PlayerCardData left, final PlayerCardData right) {
        this.card = card;
        this.top = top;
        this.bottom = bottom;
        this.left = left;
        this.right = right;
    }
}
