// Generated by delombok at Sat Oct 12 00:30:20 BRT 2024
package com.tiduswr.model;

import java.awt.Color;
import java.util.List;

/**
 * Classe que representa um jogador no jogo Triple Triad.
 */
public class Player {
    /**
     * Nome do jogador
     */
    private String name;
    /**
     * Pontos iniciais do jogador
     */
    private final int points = 5;
    /**
     * Cartas do jogador
     */
    private List<CardData> cards;
    /**
     * Cor associada ao jogador
     */
    private Color color;

    /**
     * Construtor da classe Player.
     * 
     * @param name  Nome do jogador.
     * @param cards Lista de cartas do jogador, que deve conter exatamente 5 cartas.
     * @param color Cor associada ao jogador.
     * @throws RuntimeException Se a lista de cartas não contiver exatamente 5 cartas.
     */
    public Player(String name, List<CardData> cards, Color color) {
        if (cards.size() != 5) throw new RuntimeException("A mão do jogador, inicialmente, precisa conter exatamente 5 cartas!");
        this.cards = cards;
        this.name = name;
        this.color = color;
    }

    /**
     * Nome do jogador
     */
    public String getName() {
        return this.name;
    }

    /**
     * Pontos iniciais do jogador
     */
    public int getPoints() {
        return this.points;
    }

    /**
     * Cartas do jogador
     */
    public List<CardData> getCards() {
        return this.cards;
    }

    /**
     * Cor associada ao jogador
     */
    public Color getColor() {
        return this.color;
    }
}
