// Generated by delombok at Sat Oct 12 00:30:20 BRT 2024
package com.tiduswr.model;

/**
 * Classe que representa os dados de uma carta pertencente a um jogador.
 * 
 * Essa classe permite que a mesma carta seja usada por dois jogadores diferentes.
 */
public class PlayerCardData {
    /**
     * Dados da carta
     */
    private CardData cardData;
    /**
     * Jogador que possui a carta
     */
    private Player owner;
    /**
     * Modificador utilizado para aplicar regras de jogo como Ascend e Descend. 
     *        Um valor positivo ou negativo deve ser atribuído aqui para influenciar 
     *        a comparação dos lados das cartas durante o jogo.
     */
    private int modifier;
    /**
     * Indica se a carta está virada
     */
    private boolean flipped;

    /**
     * Dados da carta
     */
    public CardData getCardData() {
        return this.cardData;
    }

    /**
     * Jogador que possui a carta
     */
    public Player getOwner() {
        return this.owner;
    }

    /**
     * Modificador utilizado para aplicar regras de jogo como Ascend e Descend. 
     *        Um valor positivo ou negativo deve ser atribuído aqui para influenciar 
     *        a comparação dos lados das cartas durante o jogo.
     */
    public int getModifier() {
        return this.modifier;
    }

    /**
     * Indica se a carta está virada
     */
    public boolean isFlipped() {
        return this.flipped;
    }

    /**
     * Dados da carta
     */
    public void setCardData(final CardData cardData) {
        this.cardData = cardData;
    }

    /**
     * Jogador que possui a carta
     */
    public void setOwner(final Player owner) {
        this.owner = owner;
    }

    /**
     * Modificador utilizado para aplicar regras de jogo como Ascend e Descend. 
     *        Um valor positivo ou negativo deve ser atribuído aqui para influenciar 
     *        a comparação dos lados das cartas durante o jogo.
     */
    public void setModifier(final int modifier) {
        this.modifier = modifier;
    }

    /**
     * Indica se a carta está virada
     */
    public void setFlipped(final boolean flipped) {
        this.flipped = flipped;
    }

    @java.lang.SuppressWarnings("all")
    public PlayerCardData(final CardData cardData, final Player owner, final int modifier, final boolean flipped) {
        this.cardData = cardData;
        this.owner = owner;
        this.modifier = modifier;
        this.flipped = flipped;
    }
}
